#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper::Compact 'ddc';
use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(MIDI-Util);
use MIDI::Util;
use Music::Chord::Progression;

my $score = MIDI::Util::setup_score();

my $net = { map { $_ => [1 .. 12] } 1 .. 12 };

my $prog = Music::Chord::Progression->new(
    net => $net,
    chords => [ ('m') x 12 ],
    scale_name => 'chromatic',
    substitute => 1,
    tonic => -1,
    resolve => -1,
    verbose => 1,
);
my $notes = $prog->generate;

for my $chord (@$notes) {
    my @chord = MIDI::Util::midi_format(@$chord);
    $score->n('wn', @chord);
}

$score->write_score("$0.mid");
